### ISSUE TITLE
Link off => Arrays em Swift - André Porto

### ISSUE THREAD

**Issue by rodrigodiasf1984** [CodandoApple/aprenda-swift#34]
https://www.linkedin.com/pulse/arrays-em-swift-andr%2525C3%2525A9-porto%25

Olá primeiramente obrigado pelo material compartilhado! Poderiam verificar o link mencionado por favor? 

Obrigado

**Comment by reisdev** [comment]
Obrigado pelo aviso, Rodrigo. O link foi quebrado em uma versão anterior após removermos um parâmetro de tracking.

Já foi resolvido [neste commit](https://github.com/CodandoApple/aprenda-swift/commit/d563cb46da73081dc02833bf4fff89de35e012f6)
